export const breedOptions = {
  Dog: [
    "Labrador Retriever",
    "Poodle",
    "German Shepherd",
    "Bulldog",
    "Beagle",
    "Golden Retriever",
    "French Bulldog",
    "Yorkshire Terrier",
    "Dachshund",
    "Boxer",
    "Shih Tzu",
    "Great Dane",
    "Siberian Husky",
    "Doberman",
    "Chihuahua",
    "Pomeranian",
    "Rottweiler",
    "Pug",
    "Border Collie",
    "Australian Shepherd",
    "Mixed Breed",
    "Other",
  ],

  Cat: [
    "Persian",
    "Siamese",
    "Maine Coon",
    "Ragdoll",
    "Bengal",
    "Sphynx",
    "British Shorthair",
    "Abyssinian",
    "Scottish Fold",
    "Devon Rex",
    "Bombay",
    "American Shorthair",
    "Burmese",
    "Russian Blue",
    "Norwegian Forest Cat",
    "Domestic Shorthair",
    "Domestic Longhair",
    "Mixed Breed",
    "Other",
  ],

  Rabbit: [
    "Dutch",
    "Lionhead",
    "Holland Lop",
    "Mini Rex",
    "Netherland Dwarf",
    "Flemish Giant",
    "Rex",
    "English Angora",
    "French Lop",
    "New Zealand",
    "Californian",
    "Mini Lop",
    "American",
    "Mixed Breed",
    "Other",
  ],

  Bird: [
    "Parakeet",
    "Canary",
    "Cockatiel",
    "Lovebird",
    "African Grey Parrot",
    "Cockatoo",
    "Macaw",
    "Conure",
    "Finch",
    "Amazon Parrot",
    "Dove",
    "Quaker Parrot",
    "Eclectus",
    "Budgie",
    "Caique",
    "Mixed Species",
    "Other",
  ],

  Reptile: [
    "Bearded Dragon",
    "Iguana",
    "Leopard Gecko",
    "Crested Gecko",
    "Ball Python",
    "Corn Snake",
    "Boa Constrictor",
    "Chameleon",
    "Tortoise",
    "Turtle",
    "Blue-Tongued Skink",
    "Water Dragon",
    "Monitor Lizard",
    "Anole",
    "Other",
  ],

  Fish: [
    "Goldfish",
    "Betta",
    "Guppy",
    "Angelfish",
    "Tetra",
    "Molly",
    "Platy",
    "Discus",
    "Cichlid",
    "Koi",
    "Oscar",
    "Cory Catfish",
    "Plecostomus",
    "Swordtail",
    "Arowana",
    "Tropical Mix",
    "Coldwater Mix",
    "Other",
  ],

  "Small Mammal": [
    "Guinea Pig",
    "Hamster",
    "Gerbil",
    "Rat",
    "Mouse",
    "Chinchilla",
    "Ferret",
    "Hedgehog",
    "Sugar Glider",
    "Degu",
    "Other",
  ],

  Horse: [
    "Arabian",
    "Quarter Horse",
    "Thoroughbred",
    "Appaloosa",
    "Mustang",
    "Morgan",
    "Paint",
    "Friesian",
    "Andalusian",
    "Clydesdale",
    "Shetland Pony",
    "Welsh Pony",
    "Mixed Breed",
    "Other",
  ],

  "Farm Animal": [
    "Chicken",
    "Duck",
    "Goose",
    "Turkey",
    "Goat",
    "Sheep",
    "Pig",
    "Cow",
    "Donkey",
    "Alpaca",
    "Llama",
    "Other",
  ],

  Amphibian: [
    "Frog",
    "Toad",
    "Salamander",
    "Newt",
    "Axolotl",
    "Tree Frog",
    "Fire-Bellied Toad",
    "Other",
  ],

  Exotic: [
    "Sugar Glider",
    "Fennec Fox",
    "Kinkajou",
    "Serval",
    "Sloth",
    "Capybara",
    "Genets",
    "Skunk",
    "Wallaby",
    "Muntjac",
    "Other",
  ],

  Insect: [
    "Tarantula",
    "Scorpion",
    "Stick Insect",
    "Mantis",
    "Millipede",
    "Cockroach",
    "Ant Colony",
    "Beetle",
    "Other",
  ],

  Other: ["Mixed Species", "Hybrid", "Unknown", "Other"],
};

export const petTypes = [
  "Dog",
  "Cat",
  "Rabbit",
  "Bird",
  "Reptile",
  "Fish",
  "Small Mammal",
  "Horse",
  "Farm Animal",
  "Amphibian",
  "Exotic",
  "Insect",
  "Other",
];
